spring.application.name=SpringBootAPI
spring.datasource.url=${RDB_URL}
spring.datasource.username= ${RDB_Username}
spring.datasource.password=${RDB_PW}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=${Spring_Sec_Username}
spring.security.user.password=${Spring_Sec_PW}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,https://rohkeymon.krowvin.com}
